"""user training consent

Revision ID: 468a1928ece1
Revises: 74ee6c67a935
Create Date: 2026-10-07 23:35:08.795807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '468a1928ece1'
down_revision: Union[str, Sequence[str], None] = '74ee6c67a935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_consent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('training_consent_version', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('training_consent_version')
        batch_op.drop_column('training_consent_at')

    # ### end Alembic commands ###
