"""review label_source and aspects

Revision ID: 74ee6c67a935
Revises: 927add20e906
Create Date: 2026-10-04 13:45:45.434367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74ee6c67a935'
down_revision: Union[str, Sequence[str], None] = '927add20e906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('aspects', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('aspects')
        batch_op.drop_column('label_source')

    # ### end Alembic commands ###
